{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: jupyter in /home/user/anaconda3/lib/python3.11/site-packages (1.0.0)\n",
      "Requirement already satisfied: ipywidgets in /home/user/anaconda3/lib/python3.11/site-packages (8.1.2)\n",
      "Requirement already satisfied: notebook in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter) (7.0.8)\n",
      "Requirement already satisfied: qtconsole in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter) (5.4.2)\n",
      "Requirement already satisfied: jupyter-console in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter) (6.6.3)\n",
      "Requirement already satisfied: nbconvert in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter) (7.10.0)\n",
      "Requirement already satisfied: ipykernel in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter) (6.28.0)\n",
      "Requirement already satisfied: comm>=0.1.3 in /home/user/anaconda3/lib/python3.11/site-packages (from ipywidgets) (0.2.2)\n",
      "Requirement already satisfied: ipython>=6.1.0 in /home/user/anaconda3/lib/python3.11/site-packages (from ipywidgets) (8.20.0)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in /home/user/anaconda3/lib/python3.11/site-packages (from ipywidgets) (5.7.1)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0.10 in /home/user/anaconda3/lib/python3.11/site-packages (from ipywidgets) (4.0.10)\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0.10 in /home/user/anaconda3/lib/python3.11/site-packages (from ipywidgets) (3.0.10)\n",
      "Requirement already satisfied: decorator in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.18.1)\n",
      "Requirement already satisfied: matplotlib-inline in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)\n",
      "Requirement already satisfied: pygments>=2.4.0 in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)\n",
      "Requirement already satisfied: stack-data in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)\n",
      "Requirement already satisfied: pexpect>4.3 in /home/user/anaconda3/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (4.8.0)\n",
      "Requirement already satisfied: debugpy>=1.6.5 in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (1.6.7)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (8.6.0)\n",
      "Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (5.5.0)\n",
      "Requirement already satisfied: nest-asyncio in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (1.6.0)\n",
      "Requirement already satisfied: packaging in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (23.1)\n",
      "Requirement already satisfied: psutil in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (5.9.0)\n",
      "Requirement already satisfied: pyzmq>=24 in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (25.1.2)\n",
      "Requirement already satisfied: tornado>=6.1 in /home/user/anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter) (6.3.3)\n",
      "Requirement already satisfied: beautifulsoup4 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (4.12.2)\n",
      "Requirement already satisfied: bleach!=5.0.0 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (4.1.0)\n",
      "Requirement already satisfied: defusedxml in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (0.7.1)\n",
      "Requirement already satisfied: jinja2>=3.0 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (3.1.3)\n",
      "Requirement already satisfied: jupyterlab-pygments in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (0.1.2)\n",
      "Requirement already satisfied: markupsafe>=2.0 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (2.1.3)\n",
      "Requirement already satisfied: mistune<4,>=2.0.3 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (2.0.4)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (0.8.0)\n",
      "Requirement already satisfied: nbformat>=5.7 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (5.9.2)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (1.5.0)\n",
      "Requirement already satisfied: tinycss2 in /home/user/anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter) (1.2.1)\n",
      "Requirement already satisfied: jupyter-server<3,>=2.4.0 in /home/user/anaconda3/lib/python3.11/site-packages (from notebook->jupyter) (2.10.0)\n",
      "Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in /home/user/anaconda3/lib/python3.11/site-packages (from notebook->jupyter) (2.25.1)\n",
      "Requirement already satisfied: jupyterlab<4.1,>=4.0.2 in /home/user/anaconda3/lib/python3.11/site-packages (from notebook->jupyter) (4.0.11)\n",
      "Requirement already satisfied: notebook-shim<0.3,>=0.2 in /home/user/anaconda3/lib/python3.11/site-packages (from notebook->jupyter) (0.2.3)\n",
      "Requirement already satisfied: ipython-genutils in /home/user/anaconda3/lib/python3.11/site-packages (from qtconsole->jupyter) (0.2.0)\n",
      "Requirement already satisfied: qtpy>=2.0.1 in /home/user/anaconda3/lib/python3.11/site-packages (from qtconsole->jupyter) (2.4.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /home/user/anaconda3/lib/python3.11/site-packages (from bleach!=5.0.0->nbconvert->jupyter) (1.16.0)\n",
      "Requirement already satisfied: webencodings in /home/user/anaconda3/lib/python3.11/site-packages (from bleach!=5.0.0->nbconvert->jupyter) (0.5.1)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (2.8.2)\n",
      "Requirement already satisfied: platformdirs>=2.5 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (3.10.0)\n",
      "Requirement already satisfied: anyio>=3.1.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (4.2.0)\n",
      "Requirement already satisfied: argon2-cffi in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (21.3.0)\n",
      "Requirement already satisfied: jupyter-events>=0.6.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.8.0)\n",
      "Requirement already satisfied: jupyter-server-terminals in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.4.4)\n",
      "Requirement already satisfied: overrides in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (7.4.0)\n",
      "Requirement already satisfied: prometheus-client in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.14.1)\n",
      "Requirement already satisfied: send2trash>=1.8.2 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.2)\n",
      "Requirement already satisfied: terminado>=0.8.3 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.17.1)\n",
      "Requirement already satisfied: websocket-client in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.58.0)\n",
      "Requirement already satisfied: async-lru>=1.0.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyterlab<4.1,>=4.0.2->notebook->jupyter) (2.0.4)\n",
      "Requirement already satisfied: jupyter-lsp>=2.0.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyterlab<4.1,>=4.0.2->notebook->jupyter) (2.2.0)\n",
      "Requirement already satisfied: babel>=2.10 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.11.0)\n",
      "Requirement already satisfied: json5>=0.9.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.9.6)\n",
      "Requirement already satisfied: jsonschema>=4.18.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (4.19.2)\n",
      "Requirement already satisfied: requests>=2.31 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.31.0)\n",
      "Requirement already satisfied: fastjsonschema in /home/user/anaconda3/lib/python3.11/site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.16.2)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /home/user/anaconda3/lib/python3.11/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /home/user/anaconda3/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.5)\n",
      "Requirement already satisfied: soupsieve>1.2 in /home/user/anaconda3/lib/python3.11/site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)\n",
      "Requirement already satisfied: executing in /home/user/anaconda3/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.8.3)\n",
      "Requirement already satisfied: asttokens in /home/user/anaconda3/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.5)\n",
      "Requirement already satisfied: pure-eval in /home/user/anaconda3/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)\n",
      "Requirement already satisfied: idna>=2.8 in /home/user/anaconda3/lib/python3.11/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (3.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in /home/user/anaconda3/lib/python3.11/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)\n",
      "Requirement already satisfied: pytz>=2015.7 in /home/user/anaconda3/lib/python3.11/site-packages (from babel>=2.10->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2023.3.post1)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.10.6)\n",
      "Requirement already satisfied: python-json-logger>=2.0.4 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.7)\n",
      "Requirement already satisfied: pyyaml>=5.3 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (6.0.1)\n",
      "Requirement already satisfied: rfc3339-validator in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.4)\n",
      "Requirement already satisfied: rfc3986-validator>=0.1.1 in /home/user/anaconda3/lib/python3.11/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/user/anaconda3/lib/python3.11/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.0.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/user/anaconda3/lib/python3.11/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.0.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/user/anaconda3/lib/python3.11/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2024.2.2)\n",
      "Requirement already satisfied: argon2-cffi-bindings in /home/user/anaconda3/lib/python3.11/site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter) (21.2.0)\n",
      "Requirement already satisfied: fqdn in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.5.1)\n",
      "Requirement already satisfied: isoduration in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (20.11.0)\n",
      "Requirement already satisfied: jsonpointer>1.13 in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.1)\n",
      "Requirement already satisfied: uri-template in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)\n",
      "Requirement already satisfied: webcolors>=1.11 in /home/user/anaconda3/lib/python3.11/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.13)\n",
      "Requirement already satisfied: cffi>=1.0.1 in /home/user/anaconda3/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.16.0)\n",
      "Requirement already satisfied: pycparser in /home/user/anaconda3/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.21)\n",
      "Requirement already satisfied: arrow>=0.15.0 in /home/user/anaconda3/lib/python3.11/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.2.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: torch in /home/user/anaconda3/lib/python3.11/site-packages (2.2.2)\n",
      "Requirement already satisfied: fairscale in /home/user/anaconda3/lib/python3.11/site-packages (0.4.13)\n",
      "Requirement already satisfied: tiktoken==0.4.0 in /home/user/anaconda3/lib/python3.11/site-packages (0.4.0)\n",
      "Requirement already satisfied: fair in /home/user/anaconda3/lib/python3.11/site-packages (2.1.4)\n",
      "Requirement already satisfied: blobfile in /home/user/anaconda3/lib/python3.11/site-packages (2.1.1)\n",
      "Requirement already satisfied: datasets in /home/user/anaconda3/lib/python3.11/site-packages (2.18.0)\n",
      "Requirement already satisfied: mwparserfromhell in /home/user/anaconda3/lib/python3.11/site-packages (0.6.6)\n",
      "Requirement already satisfied: regex>=2022.1.18 in /home/user/anaconda3/lib/python3.11/site-packages (from tiktoken==0.4.0) (2023.10.3)\n",
      "Requirement already satisfied: requests>=2.26.0 in /home/user/anaconda3/lib/python3.11/site-packages (from tiktoken==0.4.0) (2.31.0)\n",
      "Requirement already satisfied: filelock in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (4.9.0)\n",
      "Requirement already satisfied: sympy in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (1.12)\n",
      "Requirement already satisfied: networkx in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (3.1)\n",
      "Requirement already satisfied: jinja2 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (3.1.3)\n",
      "Requirement already satisfied: fsspec in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (2023.10.0)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (8.9.2.26)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (12.1.3.1)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (11.0.2.54)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (10.3.2.106)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (11.4.5.107)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (12.1.0.106)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (2.19.3)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (12.1.105)\n",
      "Requirement already satisfied: triton==2.2.0 in /home/user/anaconda3/lib/python3.11/site-packages (from torch) (2.2.0)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/user/anaconda3/lib/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.4.127)\n",
      "Requirement already satisfied: numpy>=1.22.0 in /home/user/anaconda3/lib/python3.11/site-packages (from fairscale) (1.26.4)\n",
      "Requirement already satisfied: matplotlib in /home/user/anaconda3/lib/python3.11/site-packages (from fair) (3.8.0)\n",
      "Requirement already satisfied: pandas in /home/user/anaconda3/lib/python3.11/site-packages (from fair) (2.1.4)\n",
      "Requirement already satisfied: pooch in /home/user/anaconda3/lib/python3.11/site-packages (from fair) (1.8.1)\n",
      "Requirement already satisfied: scipy in /home/user/anaconda3/lib/python3.11/site-packages (from fair) (1.11.4)\n",
      "Requirement already satisfied: tqdm in /home/user/anaconda3/lib/python3.11/site-packages (from fair) (4.65.0)\n",
      "Requirement already satisfied: xarray in /home/user/anaconda3/lib/python3.11/site-packages (from fair) (2023.6.0)\n",
      "Requirement already satisfied: pycryptodomex~=3.8 in /home/user/anaconda3/lib/python3.11/site-packages (from blobfile) (3.20.0)\n",
      "Requirement already satisfied: urllib3<3,>=1.25.3 in /home/user/anaconda3/lib/python3.11/site-packages (from blobfile) (2.0.7)\n",
      "Requirement already satisfied: lxml~=4.9 in /home/user/anaconda3/lib/python3.11/site-packages (from blobfile) (4.9.3)\n",
      "Requirement already satisfied: pyarrow>=12.0.0 in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (14.0.2)\n",
      "Requirement already satisfied: pyarrow-hotfix in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (0.6)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (0.3.8)\n",
      "Requirement already satisfied: xxhash in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (3.4.1)\n",
      "Requirement already satisfied: multiprocess in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (0.70.16)\n",
      "Requirement already satisfied: aiohttp in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (3.9.3)\n",
      "Requirement already satisfied: huggingface-hub>=0.19.4 in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (0.22.2)\n",
      "Requirement already satisfied: packaging in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (23.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /home/user/anaconda3/lib/python3.11/site-packages (from datasets) (6.0.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/user/anaconda3/lib/python3.11/site-packages (from aiohttp->datasets) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/user/anaconda3/lib/python3.11/site-packages (from aiohttp->datasets) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/user/anaconda3/lib/python3.11/site-packages (from aiohttp->datasets) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/user/anaconda3/lib/python3.11/site-packages (from aiohttp->datasets) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/user/anaconda3/lib/python3.11/site-packages (from aiohttp->datasets) (1.9.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/user/anaconda3/lib/python3.11/site-packages (from requests>=2.26.0->tiktoken==0.4.0) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/user/anaconda3/lib/python3.11/site-packages (from requests>=2.26.0->tiktoken==0.4.0) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/user/anaconda3/lib/python3.11/site-packages (from requests>=2.26.0->tiktoken==0.4.0) (2024.2.2)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/user/anaconda3/lib/python3.11/site-packages (from jinja2->torch) (2.1.3)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (4.25.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (1.4.4)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (10.2.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (3.0.9)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /home/user/anaconda3/lib/python3.11/site-packages (from matplotlib->fair) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/user/anaconda3/lib/python3.11/site-packages (from pandas->fair) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /home/user/anaconda3/lib/python3.11/site-packages (from pandas->fair) (2023.3)\n",
      "Requirement already satisfied: platformdirs>=2.5.0 in /home/user/anaconda3/lib/python3.11/site-packages (from pooch->fair) (3.10.0)\n",
      "Requirement already satisfied: mpmath>=0.19 in /home/user/anaconda3/lib/python3.11/site-packages (from sympy->torch) (1.3.0)\n",
      "Requirement already satisfied: six>=1.5 in /home/user/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->fair) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install --upgrade jupyter ipywidgets\n",
    "%pip install torch fairscale tiktoken==0.4.0 fair blobfile datasets mwparserfromhell"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> initializing model parallel with size 1\n",
      "> initializing ddp with size 1\n",
      "> initializing pipeline with size 1\n",
      "Layer state dict saved to data/layer_0.pt\n",
      "Layer state dict saved to data/layer_1.pt\n",
      "Layer state dict saved to data/layer_2.pt\n",
      "Layer state dict saved to data/layer_3.pt\n",
      "Layer state dict saved to data/embedding.pt\n",
      "Layer state dict saved to data/output.pt\n",
      "Saved to data/freqs_cis.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 1/3: 0it [00:00, ?it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting content from https://dumps.wikimedia.org/enwiki/20240401/enwiki-20240401-pages-articles-multistream1.xml-p1p41242.bz2\n",
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 0: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 1it [00:59, 59.88s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 1: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 2it [01:08, 29.45s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 2: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 3it [01:15, 19.61s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 3: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 4it [01:24, 15.13s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 4: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 5it [01:32, 12.55s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 5: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 6it [01:40, 10.98s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 6: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 7it [01:48,  9.99s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 7: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 8it [01:56,  9.48s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 8: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 9it [02:04,  9.03s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 9: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 10it [02:12,  8.73s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 10: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 11it [02:20,  8.57s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 11: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 12it [02:28,  8.46s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 12: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 13it [02:37,  8.40s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 13: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 14it [02:45,  8.22s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 14: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 15it [02:53,  8.17s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 15: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 16it [03:01,  8.24s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 16: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 17it [03:09,  8.09s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 17: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 18it [03:17,  8.10s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 18: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 19it [03:25,  8.16s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 19: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 20it [03:33,  8.14s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 20: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 21it [03:41,  8.07s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 21: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 22it [03:49,  8.07s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 22: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 23it [03:57,  8.06s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 23: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 24it [04:05,  8.00s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 24: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 25it [04:13,  7.88s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 25: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 26it [04:20,  7.80s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 26: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 27it [04:28,  7.81s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 27: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 28it [04:36,  7.90s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 28: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 29it [04:44,  7.84s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 29: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 30it [04:52,  7.83s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 30: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 31it [05:00,  7.88s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 31: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 32it [05:07,  7.82s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 32: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 33it [05:15,  7.83s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 33: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 34it [05:23,  7.79s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 34: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 35it [05:31,  7.90s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 35: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 36it [05:39,  7.81s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 36: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 37it [05:46,  7.76s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 37: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 38it [05:54,  7.78s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 38: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 39it [06:02,  7.72s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 39: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 40it [06:09,  7.68s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 40: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 41it [06:17,  7.62s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 41: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 42it [06:25,  7.68s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 42: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 43it [06:32,  7.66s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 43: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 44it [06:40,  7.69s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 44: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 45it [06:48,  7.66s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 45: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 46it [06:55,  7.69s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 46: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 47it [07:03,  7.78s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 47: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 48it [07:11,  7.77s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 48: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 49it [07:19,  7.68s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 49: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 50it [07:27,  7.74s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 50: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 51it [07:34,  7.77s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 51: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 52it [07:42,  7.79s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 52: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 53it [07:50,  7.72s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 53: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 54it [07:58,  7.75s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 54: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 55it [08:05,  7.70s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 55: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 56it [08:13,  7.85s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 56: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 57it [08:21,  7.90s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n",
      "Loaded from data/logits_layer_3.pt\n",
      "Saved to data/final_inputs.pt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' failed with error: Traceback (most recent call last):\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 238, in <module>\n",
      "    norm_task(args.inputs, args.norm_file, args.normed_output)\n",
      "  File \"/home/user/Coding/ritser/magnum/spl/worker.py\", line 186, in norm_task\n",
      "    norm.load_state_dict(load_layer_state_dict(norm_file))\n",
      "  File \"/home/user/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 2104, in load_state_dict\n",
      "    raise TypeError(f\"Expected state_dict to be dict-like, got {type(state_dict)}.\")\n",
      "TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.\n",
      "\n",
      "ERROR:root:Failed to process and save batch: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "ERROR:root:Error processing batch at step 57: Command 'python3 worker.py --task norm --inputs data/final_inputs.pt --norm_file data/norm.pt --normed_output data/normed_output.pt' returned non-zero exit status 1.\n",
      "Epoch 1/3: 58it [08:30,  8.10s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved to data/batch.pt\n",
      "Loaded from data/inputs.pt\n",
      "Loaded from data/freqs_cis.pt\n",
      "Saved to data/freqs_cis.pt\n",
      "Saved to data/inputs_layer_0.pt\n",
      "Loaded from data/logits_layer_0.pt\n",
      "Saved to data/inputs_layer_1.pt\n",
      "Loaded from data/logits_layer_1.pt\n",
      "Saved to data/inputs_layer_2.pt\n",
      "Loaded from data/logits_layer_2.pt\n",
      "Saved to data/inputs_layer_3.pt\n"
     ]
    }
   ],
   "source": [
    "import logging\n",
    "import subprocess\n",
    "import torch\n",
    "import torch.distributed as dist\n",
    "from common import save_to_disk, load_from_disk, save_layer_state_dict, load_layer_state_dict, model_args, tokenizer\n",
    "from tokenizer import Tokenizer\n",
    "from datasets import load_dataset\n",
    "from torch.utils.data import DataLoader, IterableDataset\n",
    "import os\n",
    "import time\n",
    "from tqdm import tqdm\n",
    "from model import TransformerBlock, VocabParallelEmbedding, ColumnParallelLinear, RMSNorm, Transformer, precompute_freqs_cis\n",
    "from fairscale.nn.model_parallel.initialize import initialize_model_parallel, model_parallel_is_initialized\n",
    "\n",
    "class StreamingWikipediaDataset(IterableDataset):\n",
    "    def __init__(self, texts, tokenizer, seq_len):\n",
    "        self.texts = texts\n",
    "        self.tokenizer = tokenizer\n",
    "        self.seq_len = seq_len\n",
    "\n",
    "    def parse(self, text):\n",
    "        tokens = self.tokenizer.encode(text, bos=True, eos=True)\n",
    "        tokens = tokens[:self.seq_len] + [self.tokenizer.pad_id] * (self.seq_len - len(tokens))\n",
    "        return torch.tensor(tokens)\n",
    "\n",
    "    def __iter__(self):\n",
    "        for item in self.texts:\n",
    "            yield self.parse(item['text'])\n",
    "\n",
    "def wait_for_file(filename, timeout=30):\n",
    "    start_time = time.time()\n",
    "    while not os.path.exists(filename):\n",
    "        if time.time() - start_time > timeout:\n",
    "            raise TimeoutError(f\"Timeout waiting for {filename}\")\n",
    "        time.sleep(0.1)\n",
    "\n",
    "def initialize_layers(model_args):\n",
    "    # Initialize and save state dicts for all layers\n",
    "    for layer_idx in range(model_args.n_layers):\n",
    "        layer = TransformerBlock(layer_idx, model_args)\n",
    "        save_layer_state_dict(layer.state_dict(), f\"data/layer_{layer_idx}.pt\")\n",
    "    \n",
    "    # Save the state dict for the embedding and output layers\n",
    "    embedding = VocabParallelEmbedding(model_args.vocab_size, model_args.dim)\n",
    "    save_layer_state_dict(embedding.state_dict(), \"data/embedding.pt\")\n",
    "    \n",
    "    output = ColumnParallelLinear(model_args.dim, model_args.vocab_size, bias=False)\n",
    "    save_layer_state_dict(output.state_dict(), \"data/output.pt\")\n",
    "\n",
    "    freqs_cis = precompute_freqs_cis(\n",
    "        model_args.dim // model_args.n_heads,\n",
    "        model_args.max_seq_len * 2,\n",
    "        model_args.rope_theta,\n",
    "    )\n",
    "    save_to_disk(freqs_cis, \"data/freqs_cis.pt\")\n",
    "\n",
    "def main():\n",
    "    # Set environment variables for distributed training\n",
    "    os.environ['MASTER_ADDR'] = 'localhost'\n",
    "    os.environ['MASTER_PORT'] = '12355'\n",
    "    os.environ['WORLD_SIZE'] = '1'\n",
    "    os.environ['RANK'] = '0'\n",
    "    \n",
    "    # Initialize distributed environment\n",
    "    dist.init_process_group(backend='nccl')\n",
    "    initialize_model_parallel(model_parallel_size_=1)\n",
    "    \n",
    "    # Load the dataset using streaming\n",
    "    dataset = load_dataset(\"wikipedia\", language=\"en\", date=\"20240401\", split='train', streaming=True, trust_remote_code=True)\n",
    "    \n",
    "    # Prepare the dataset and dataloader\n",
    "    seq_len = 2048\n",
    "    wiki_dataset = StreamingWikipediaDataset(dataset, tokenizer, seq_len)\n",
    "    dataloader = DataLoader(wiki_dataset, batch_size=1, shuffle=False, num_workers=0)\n",
    "\n",
    "    num_epochs = 3\n",
    "    learning_rate = 1e-4\n",
    "    beta1 = 0.9\n",
    "    beta2 = 0.999\n",
    "    epsilon = 1e-8\n",
    "    weight_decay = 1e-2\n",
    "\n",
    "    # Initialize layer state dictionaries\n",
    "    initialize_layers(model_args)\n",
    "\n",
    "    for epoch in range(num_epochs):\n",
    "        epoch_loss = 0\n",
    "\n",
    "        for step, batch in enumerate(tqdm(dataloader, desc=f\"Epoch {epoch + 1}/{num_epochs}\")):\n",
    "            try:\n",
    "                process_batch(batch, tokenizer, epoch_loss, learning_rate, beta1, beta2, epsilon, weight_decay, step + 1)\n",
    "            except Exception as e:\n",
    "                logging.error(f\"Error processing batch at step {step}: {e}\")\n",
    "                continue \n",
    "\n",
    "        print(f\"Epoch {epoch + 1} Loss: {epoch_loss / len(dataloader)}\")\n",
    "        \n",
    "        dist.destroy_process_group()\n",
    "\n",
    "def process_batch(batch, tokenizer, epoch_loss, learning_rate, beta1, beta2, epsilon, weight_decay, t):\n",
    "    try:\n",
    "        batch = batch.to('cpu')\n",
    "        save_to_disk(batch, \"data/batch.pt\")\n",
    "        run_command(f\"python3 worker.py --task embed --batch data/batch.pt --embedding_file data/embedding.pt --inputs data/inputs.pt\")\n",
    "        wait_for_file(\"data/inputs.pt\")\n",
    "        inputs = load_from_disk(\"data/inputs.pt\")\n",
    "\n",
    "        freqs_cis = load_from_disk(\"data/freqs_cis.pt\")\n",
    "        save_to_disk(freqs_cis, \"data/freqs_cis.pt\")\n",
    "\n",
    "        for layer_idx in range(model_args.n_layers):\n",
    "            inputs_file = f\"data/inputs_layer_{layer_idx}.pt\"\n",
    "            logits_file = f\"data/logits_layer_{layer_idx}.pt\"\n",
    "            state_dict_file = f\"data/layer_{layer_idx}.pt\"\n",
    "            save_to_disk(inputs, inputs_file)\n",
    "            run_command(f\"python3 worker.py --task forward --layer_idx {layer_idx} --inputs {inputs_file} --state_dict {state_dict_file} --freqs_cis data/freqs_cis.pt --logits_file {logits_file}\")\n",
    "            wait_for_file(logits_file)\n",
    "            inputs = load_from_disk(logits_file)\n",
    "\n",
    "        norm = RMSNorm(model_args.dim, eps=model_args.norm_eps)\n",
    "        inputs = norm(inputs)\n",
    "        save_to_disk(inputs, \"data/final_inputs.pt\")\n",
    "\n",
    "        run_command(f\"python3 worker.py --task final_logits --inputs data/final_inputs.pt --state_dict data/output.pt --logits_file data/logits.pt\")\n",
    "        wait_for_file(\"data/logits.pt\")\n",
    "        logits = load_from_disk(\"data/logits.pt\")\n",
    "        \n",
    "        save_to_disk(batch, \"data/targets.pt\")\n",
    "        save_to_disk(logits, \"data/logits.pt\")\n",
    "        run_command(f\"python3 worker.py --task loss --logits data/logits.pt --targets data/targets.pt --loss_file data/loss.pt --logits_grad_file data/logits_grad.pt\")\n",
    "        wait_for_file(\"data/loss.pt\")\n",
    "        wait_for_file(\"data/logits_grad.pt\")\n",
    "        \n",
    "        loss = load_from_disk(\"data/loss.pt\")\n",
    "        print(f\"Loss: {loss:.4f}\")\n",
    "        epoch_loss += loss\n",
    "        logits_grad = load_from_disk(\"data/logits_grad.pt\")\n",
    "        \n",
    "        # Backpropagate through the output layer\n",
    "        save_to_disk(logits_grad, \"data/final_error.pt\")\n",
    "        run_command(f\"python3 worker.py --task final_logits_backward --error data/final_error.pt --inputs data/final_inputs.pt --state_dict data/output.pt --error_output_file data/error_output.pt\")\n",
    "        wait_for_file(\"data/error_output.pt\")\n",
    "        final_error, output_grads = load_from_disk(\"data/error_output.pt\")\n",
    "        save_to_disk(output_grads, \"data/output_grads.pt\")\n",
    "        run_command(f\"python3 worker.py --task apply_adamw --layer_idx -1 --grads data/output_grads.pt --learning_rate {learning_rate} --beta1 {beta1} --beta2 {beta2} --epsilon {epsilon} --weight_decay {weight_decay} --t {t}\")\n",
    "\n",
    "        error = final_error[0]  # Use the input gradient for the next backward pass\n",
    "        for layer_idx in reversed(range(model_args.n_layers)):\n",
    "            inputs_file = f\"data/inputs_layer_{layer_idx}.pt\"\n",
    "            error_output_file = f\"data/error_layer_{layer_idx}.pt\"\n",
    "            state_dict_file = f\"data/layer_{layer_idx}.pt\"\n",
    "            save_to_disk(error, \"data/error_for_layer.pt\")\n",
    "            run_command(f\"python3 worker.py --task backward --layer_idx {layer_idx} --error data/error_for_layer.pt --inputs {inputs_file} --state_dict {state_dict_file} --error_output_file {error_output_file}\")\n",
    "            wait_for_file(error_output_file)\n",
    "            error_grads = load_from_disk(error_output_file)\n",
    "            if error_grads is None or len(error_grads) != 2:\n",
    "                raise ValueError(f\"Failed to load error and grads from {error_output_file}\")\n",
    "            error, grads = error_grads\n",
    "            error = error.view(1, -1, model_args.dim)  # Reshape to match the output shape of the previous layer\n",
    "            save_to_disk(grads, f\"data/grads_layer_{layer_idx}.pt\")\n",
    "            run_command(f\"python3 worker.py --task apply_adamw --layer_idx {layer_idx} --grads data/grads_layer_{layer_idx}.pt --learning_rate {learning_rate} --beta1 {beta1} --beta2 {beta2} --epsilon {epsilon} --weight_decay {weight_decay} --t {t}\")\n",
    "\n",
    "        # Backpropagate through the embedding layer\n",
    "        error = error.view(batch.size(0), -1, model_args.dim)  # Reshape to match the embedding layer output\n",
    "        save_to_disk(error, \"data/embedding_error.pt\")\n",
    "        run_command(f\"python3 worker.py --task embed_backward --error data/embedding_error.pt --batch data/batch.pt --embedding_file data/embedding.pt --error_output_file data/embedding_grads.pt\")\n",
    "        wait_for_file(\"data/embedding_grads.pt\")\n",
    "        embedding_grads = load_from_disk(\"data/embedding_grads.pt\")\n",
    "        save_to_disk(embedding_grads, \"data/embedding_grads.pt\")\n",
    "        run_command(f\"python3 worker.py --task apply_adamw --layer_idx -2 --grads data/embedding_grads.pt --learning_rate {learning_rate} --beta1 {beta1} --beta2 {beta2} --epsilon {epsilon} --weight_decay {weight_decay} --t {t}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Failed to process and save batch: {e}\")\n",
    "        raise\n",
    "\n",
    "def run_command(command):\n",
    "    try:\n",
    "        result = subprocess.run(command, shell=True, text=True, capture_output=True, check=True)\n",
    "        logging.info(result.stdout)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        logging.error(f\"Command '{command}' failed with error: {e.stderr}\")\n",
    "        raise\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
